version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-app-karsajobs:
    executor: docker/docker
    environment:
      IMAGE_NAME: ghcr.io/ndaday/karsajobs_ui
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Github Container Registry
          command: echo $PAT | docker login ghcr.io --username phanatic --password-stdin

workflows:
  ci:
    jobs:
      - docker/hadolint:
          dockerfiles: './Dockerfile'
      - build-app-karsajobs:
          requires:
            - docker/hadolint
